/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as NutritionIndexRouteImport } from './routes/nutrition.index'
import { Route as NutritionSlugRouteImport } from './routes/nutrition.$slug'
import { Route as SessionWorkoutIdRouteImport } from './routes/session.$workoutId'
import { Route as WorkoutsIndexRouteImport } from './routes/workouts.index'
import { Route as WorkoutsWorkoutIdRouteImport } from './routes/workouts.$workoutId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionIndexRoute = NutritionIndexRouteImport.update({
  id: '/nutrition/',
  path: '/nutrition/',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionSlugRoute = NutritionSlugRouteImport.update({
  id: '/nutrition/$slug',
  path: '/nutrition/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionWorkoutIdRoute = SessionWorkoutIdRouteImport.update({
  id: '/session/$workoutId',
  path: '/session/$workoutId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsIndexRoute = WorkoutsIndexRouteImport.update({
  id: '/workouts/',
  path: '/workouts/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsWorkoutIdRoute = WorkoutsWorkoutIdRouteImport.update({
  id: '/workouts/$workoutId',
  path: '/workouts/$workoutId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/progress': typeof ProgressRoute
  '/nutrition/$slug': typeof NutritionSlugRoute
  '/session/$workoutId': typeof SessionWorkoutIdRoute
  '/workouts/$workoutId': typeof WorkoutsWorkoutIdRoute
  '/nutrition/': typeof NutritionIndexRoute
  '/workouts/': typeof WorkoutsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/progress': typeof ProgressRoute
  '/nutrition/$slug': typeof NutritionSlugRoute
  '/session/$workoutId': typeof SessionWorkoutIdRoute
  '/workouts/$workoutId': typeof WorkoutsWorkoutIdRoute
  '/nutrition': typeof NutritionIndexRoute
  '/workouts': typeof WorkoutsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/progress': typeof ProgressRoute
  '/nutrition/$slug': typeof NutritionSlugRoute
  '/session/$workoutId': typeof SessionWorkoutIdRoute
  '/workouts/$workoutId': typeof WorkoutsWorkoutIdRoute
  '/nutrition/': typeof NutritionIndexRoute
  '/workouts/': typeof WorkoutsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/progress'
    | '/nutrition/$slug'
    | '/session/$workoutId'
    | '/workouts/$workoutId'
    | '/nutrition/'
    | '/workouts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/progress'
    | '/nutrition/$slug'
    | '/session/$workoutId'
    | '/workouts/$workoutId'
    | '/nutrition'
    | '/workouts'
  id:
    | '__root__'
    | '/'
    | '/onboarding'
    | '/progress'
    | '/nutrition/$slug'
    | '/session/$workoutId'
    | '/workouts/$workoutId'
    | '/nutrition/'
    | '/workouts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingRoute: typeof OnboardingRoute
  ProgressRoute: typeof ProgressRoute
  NutritionSlugRoute: typeof NutritionSlugRoute
  SessionWorkoutIdRoute: typeof SessionWorkoutIdRoute
  WorkoutsWorkoutIdRoute: typeof WorkoutsWorkoutIdRoute
  NutritionIndexRoute: typeof NutritionIndexRoute
  WorkoutsIndexRoute: typeof WorkoutsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition/': {
      id: '/nutrition/'
      path: '/nutrition'
      fullPath: '/nutrition/'
      preLoaderRoute: typeof NutritionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition/$slug': {
      id: '/nutrition/$slug'
      path: '/nutrition/$slug'
      fullPath: '/nutrition/$slug'
      preLoaderRoute: typeof NutritionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$workoutId': {
      id: '/session/$workoutId'
      path: '/session/$workoutId'
      fullPath: '/session/$workoutId'
      preLoaderRoute: typeof SessionWorkoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/': {
      id: '/workouts/'
      path: '/workouts'
      fullPath: '/workouts/'
      preLoaderRoute: typeof WorkoutsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/$workoutId': {
      id: '/workouts/$workoutId'
      path: '/workouts/$workoutId'
      fullPath: '/workouts/$workoutId'
      preLoaderRoute: typeof WorkoutsWorkoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRoute: OnboardingRoute,
  ProgressRoute: ProgressRoute,
  NutritionSlugRoute: NutritionSlugRoute,
  SessionWorkoutIdRoute: SessionWorkoutIdRoute,
  WorkoutsWorkoutIdRoute: WorkoutsWorkoutIdRoute,
  NutritionIndexRoute: NutritionIndexRoute,
  WorkoutsIndexRoute: WorkoutsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
